ALL_BOARDS=
XILINX_BOARDS=

define DECLARE_XILINX_BOARD=
$1_FPGA_FAMILY=$2
$1_FPGA_ARCH=$3
$1_FPGA_PART=$4
$1_XDC=$5
$1_TOP=$6
$1_VERILOG=$7
$1_VHDL=$8
$1_VHDL_ELABORATE=$9
ALL_BOARDS+=$1
XILINX_BOARDS+=$1
endef
